
services:
   
    web:
        image: ian/php-nginx
        ports:
            - "8080:8080"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf        




